### ISSUE TITLE
Error while exporting old medium stories

### ISSUE THREAD

**Issue by maikch** [xdamman/mediumexporter#1]
Hey, I'm getting this strange error messages when exporting some old medium stories. Here's the stacktrace:

```
/usr/local/lib/node_modules/mediumexporter/index.js:24
  var s = json.payload.value;
                      ^

TypeError: Cannot read property 'value' of undefined
    at /usr/local/lib/node_modules/mediumexporter/index.js:24:23
    at Request._callback (/usr/local/lib/node_modules/mediumexporter/utils.js:12:16)
    at Request.self.callback (/usr/local/lib/node_modules/mediumexporter/node_modules/request/request.js:198:22)
    at emitTwo (events.js:87:13)
    at Request.emit (events.js:172:7)
    at Request.<anonymous> (/usr/local/lib/node_modules/mediumexporter/node_modules/request/request.js:1035:10)
    at emitOne (events.js:82:20)
    at Request.emit (events.js:169:7)
    at IncomingMessage.<anonymous>
```
¿Do you know what the problem might be? If it's a bug, with a few pointers I could help you fix it (I'm a JS programmer myself).

Here are some stories where I get the problem:

https://medium.com/keep-learning-keep-growing/how-to-enjoy-reading-books-2d10d13905c7
https://blog.zenze.co/how-to-become-fearless-ffa74f881c4f 
https://blog.zenze.co/are-you-unnecessarily-busy-b271cadb7b4e 

Thanks!

**Comment by maikch** [comment]
OK, I figured it out. 

It was the link. I changed the ones that started with blog.zenze.co to medium.com/zenze and it worked.
