### ISSUE TITLE
SyntaxError: Unexpected end of JSON input

### ISSUE THREAD

**Issue by Karlheinzniebuhr** [xdamman/mediumexporter#2]
I'm getting this error 

<pre><code>
SyntaxError: Unexpected end of JSON input
    at Object.parse (native)
    at Request._callback (/usr/local/lib/node_modules/mediumexporter/utils.js:11:25)
    at Request.self.callback (/usr/local/lib/node_modules/mediumexporter/node_modules/request/request.js:186:22)
    at emitTwo (events.js:106:13)
    at Request.emit (events.js:191:7)
    at Request.<anonymous> (/usr/local/lib/node_modules/mediumexporter/node_modules/request/request.js:1081:10)
    at emitOne (events.js:96:13)
    at Request.emit (events.js:188:7)
    at IncomingMessage.<anonymous> (/usr/local/lib/node_modules/mediumexporter/node_modules/request/request.js:1001:12)
    at IncomingMessage.g (events.js:286:16)
</code></pre>

**Comment by xdamman** [comment]
Thank you. It's fixed.

**Comment by wavebeem** [comment]
Thanks!
